Can configure admin to add and delete permissions
fabiocaccamo/django-extra-settings pull request #117
Opened 2023-11-14 02:33 UTC by web222vip

![image](https://github.com/fabiocaccamo/django-extra-settings/assets/125874410/26f789f1-49c7-4471-b9e8-1193c0dfeef8)

2023-11-14 08:40 UTC, fabiocaccamo commented
@web222vip please try to always open an issue before opening a PR.

Why don't using django's permission system?

2023-11-14 08:43 UTC, fabiocaccamo requested changes
Maybe I'm not understanding well, but why don't just use the default django's permissions system?

2023-11-14 08:43 UTC, fabiocaccamo commented on extra_settings/admin.py
> +        if settings.EXTRA_SETTINGS_ADMIN_ADD_PERMISSIO:
There is a typo in the setting name, it should be `.._PERMISSION`.

2023-11-14 08:43 UTC, fabiocaccamo commented on extra_settings/admin.py
> +        return super().has_delete_permission(request, obj)
There is a typo in the setting name, it should be `.._PERMISSION`.

2023-11-14 08:43 UTC, fabiocaccamo commented on extra_settings/admin.py
> +            return False
If the setting value is `True`, the function should return `True` instead of `False`.

2023-11-14 08:43 UTC, fabiocaccamo commented on extra_settings/admin.py
> +            return False
If the setting value is `True`, the function should return `True` instead of `False`.

2023-11-15 09:56 UTC, web222vip commented
You're right, 
Use the default django permission system

2023-11-15 09:56 UTC, closed without merging